{
  "openapi": "3.0.2",
  "info": {
    "title": "Klaviyo API",
    "version": "2026-04-15",
    "description": "The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.",
    "contact": {
      "name": "Klaviyo Developer Experience Team",
      "email": "developers@klaviyo.com",
      "url": "https://developers.klaviyo.com"
    },
    "termsOfService": "https://www.klaviyo.com/legal/api-terms",
    "license": {
      "name": "License",
      "url": "https://www.klaviyo.com/legal"
    }
  },
  "servers": [
    {
      "url": "https://a.klaviyo.com",
      "description": "Production"
    }
  ],
  "security": [
    {
      "Klaviyo-API-Key": []
    }
  ],
  "paths": {
    "/api/lists": {
      "get": {
        "operationId": "get_lists",
        "summary": "Get Lists",
        "description": "Get all lists in an account.\n\nFilter to request a subset of all lists. Lists can be filtered by `id`, `name`, `created`, and `updated` fields.\n\nReturns a maximum of 10 results per page.<br><br>*Rate limits*:<br>Burst: `75/s`<br>Steady: `750/m`\n\n**Scopes:**\n`lists:read`",
        "tags": [
          "Lists"
        ],
        "x-klaviyo-pre-release": "None",
        "x-klaviyo-ratelimit": {
          "burst": "75/s",
          "steady": "750/m"
        },
        "x-klaviyo-scopes": [
          "lists:read"
        ]
      },
      "post": {
        "operationId": "create_list",
        "summary": "Create List",
        "description": "Create a new list.<br><br>*Rate limits*:<br>Burst: `10/s`<br>Steady: `150/m`<br>Daily: `150/d`\n\n**Scopes:**\n`lists:write`",
        "tags": [
          "Lists"
        ],
        "x-klaviyo-pre-release": "None",
        "x-klaviyo-ratelimit": {
          "burst": "10/s",
          "steady": "150/m",
          "daily": "150/d"
        },
        "x-klaviyo-scopes": [
          "lists:write"
        ]
      }
    },
    "/api/lists/{id}": {
      "get": {
        "operationId": "get_list",
        "summary": "Get List",
        "description": "Get a list with the given list ID.<br><br>*Rate limits*:<br>Burst: `75/s`<br>Steady: `750/m`<br><br>Rate limits when using the `additional-fields[list]=profile_count` parameter in your API request:<br>Burst: `1/s`<br>Steady: `15/m`<br><br>To learn more about how the `additional-fields` parameter impacts rate limits, check out our [Rate limits, status codes, and errors](https://developers.klaviyo.com/en/v2026-04-15/docs/rate_limits_and_error_handling) guide.\n\n**Scopes:**[...]",
        "tags": [
          "Lists"
        ],
        "x-klaviyo-pre-release": "None",
        "x-klaviyo-ratelimit": {
          "burst": "75/s",
          "steady": "750/m"
        },
        "x-klaviyo-scopes": [
          "lists:read"
        ]
      },
      "patch": {
        "operationId": "update_list",
        "summary": "Update List",
        "description": "Update the name of a list with the given list ID.<br><br>*Rate limits*:<br>Burst: `10/s`<br>Steady: `150/m`\n\n**Scopes:**\n`lists:write`",
        "tags": [
          "Lists"
        ],
        "x-klaviyo-pre-release": "None",
        "x-klaviyo-ratelimit": {
          "burst": "10/s",
          "steady": "150/m"
        },
        "x-klaviyo-scopes": [
          "lists:write"
        ]
      },
      "delete": {
        "operationId": "delete_list",
        "summary": "Delete List",
        "description": "Delete a list with the given list ID.<br><br>*Rate limits*:<br>Burst: `10/s`<br>Steady: `150/m`\n\n**Scopes:**\n`lists:write`",
        "tags": [
          "Lists"
        ],
        "x-klaviyo-pre-release": "None",
        "x-klaviyo-ratelimit": {
          "burst": "10/s",
          "steady": "150/m"
        },
        "x-klaviyo-scopes": [
          "lists:write"
        ]
      }
    },
    "/api/lists/{id}/tags": {
      "get": {
        "operationId": "get_tags_for_list",
        "summary": "Get Tags for List",
        "description": "Return all tags associated with the given list ID.<br><br>*Rate limits*:<br>Burst: `3/s`<br>Steady: `60/m`\n\n**Scopes:**\n`lists:read`\n`tags:read`",
        "tags": [
          "Lists"
        ],
        "x-klaviyo-operation-aliases": [
          "get_list_tags"
        ],
        "x-klaviyo-pre-release": "None",
        "x-klaviyo-ratelimit": {
          "burst": "3/s",
          "steady": "60/m"
        },
        "x-klaviyo-scopes": [
          "lists:read",
          "tags:read"
        ]
      }
    },
    "/api/lists/{id}/relationships/tags": {
      "get": {
        "operationId": "get_tag_ids_for_list",
        "summary": "Get Tag IDs for List",
        "description": "Return all tags associated with the given list ID.<br><br>*Rate limits*:<br>Burst: `3/s`<br>Steady: `60/m`\n\n**Scopes:**\n`lists:read`\n`tags:read`",
        "tags": [
          "Lists"
        ],
        "x-klaviyo-operation-aliases": [
          "get_list_relationships_tags"
        ],
        "x-klaviyo-pre-release": "None",
        "x-klaviyo-ratelimit": {
          "burst": "3/s",
          "steady": "60/m"
        },
        "x-klaviyo-scopes": [
          "lists:read",
          "tags:read"
        ]
      }
    },
    "/api/lists/{id}/profiles": {
      "get": {
        "operationId": "get_profiles_for_list",
        "summary": "Get Profiles for List",
        "description": "Get all profiles within a list with the given list ID.\n\nFilter to request a subset of all profiles. Profiles can be filtered by `email`, `phone_number`, `push_token`, and `joined_group_at` fields. Profiles can be sorted by the following fields, in ascending and descending order: `joined_group_at`<br><br>*Rate limits*:<br>Burst: `75/s`<br>Steady: `750/m`<br><br>Rate limits when using the `additional-fields[profile]=predictive_analytics` parameter in your API request:<br>[...]",
        "tags": [
          "Lists"
        ],
        "x-klaviyo-operation-aliases": [
          "get_list_profiles"
        ],
        "x-klaviyo-pre-release": "None",
        "x-klaviyo-ratelimit": {
          "burst": "75/s",
          "steady": "750/m"
        },
        "x-klaviyo-scopes": [
          "lists:read",
          "profiles:read"
        ]
      }
    },
    "/api/lists/{id}/relationships/profiles": {
      "get": {
        "operationId": "get_profile_ids_for_list",
        "summary": "Get Profile IDs for List",
        "description": "Get profile membership [relationships](https://developers.klaviyo.com/en/reference/api_overview#relationships) for a list with the given list ID.<br><br>*Rate limits*:<br>Burst: `75/s`<br>Steady: `750/m`<br><br>Rate limits when using the `additional-fields[profile]=predictive_analytics` parameter in your API request:<br>Burst: `10/s`<br>Steady: `150/m`<br><br>To learn more about how the `additional-fields` parameter impacts rate limits, check out our [Rate limits, status [...]",
        "tags": [
          "Lists"
        ],
        "x-klaviyo-operation-aliases": [
          "get_list_relationships_profiles"
        ],
        "x-klaviyo-pre-release": "None",
        "x-klaviyo-ratelimit": {
          "burst": "75/s",
          "steady": "750/m"
        },
        "x-klaviyo-scopes": [
          "lists:read",
          "profiles:read"
        ]
      },
      "post": {
        "operationId": "add_profiles_to_list",
        "summary": "Add Profiles to List",
        "description": "Add a profile to a list with the given list ID.\n\nIt is recommended that you use the [Subscribe Profiles endpoint](https://developers.klaviyo.com/en/reference/subscribe_profiles) if you're trying to give a profile [consent](https://developers.klaviyo.com/en/docs/collect_email_and_sms_consent_via_api) to receive email marketing, SMS marketing, or both.\n\nThis endpoint accepts a maximum of 1000 profiles per call.<br><br>*Rate limits*:<br>Burst: `10/s`<br>Steady: `150/m`\n[...]",
        "tags": [
          "Lists"
        ],
        "x-klaviyo-operation-aliases": [
          "create_list_relationships",
          "create_list_relationships_profile",
          "create_list_relationships_profiles"
        ],
        "x-klaviyo-pre-release": "None",
        "x-klaviyo-ratelimit": {
          "burst": "10/s",
          "steady": "150/m"
        },
        "x-klaviyo-scopes": [
          "lists:write",
          "profiles:write"
        ]
      },
      "delete": {
        "operationId": "remove_profiles_from_list",
        "summary": "Remove Profiles from List",
        "description": "Remove a profile from a list with the given list ID.\n\nThe provided profile will no longer receive marketing from this particular list once removed.\n\nRemoving a profile from a list will not impact the profile's [consent](https://developers.klaviyo.com/en/docs/collect_email_and_sms_consent_via_api) status or subscription status in general.\nTo update a profile's subscription status, please use the [Unsubscribe Profiles endpoint](https://developers.klaviyo.com/en/referen[...]",
        "tags": [
          "Lists"
        ],
        "x-klaviyo-operation-aliases": [
          "delete_list_relationships",
          "delete_list_relationships_profiles"
        ],
        "x-klaviyo-pre-release": "None",
        "x-klaviyo-ratelimit": {
          "burst": "10/s",
          "steady": "150/m"
        },
        "x-klaviyo-scopes": [
          "lists:write",
          "profiles:write"
        ]
      }
    },
    "/api/lists/{id}/flow-triggers": {
      "get": {
        "operationId": "get_flows_triggered_by_list",
        "summary": "Get Flows Triggered by List",
        "description": "Get all flows where the given list ID is being used as the trigger.<br><br>*Rate limits*:<br>Burst: `3/s`<br>Steady: `60/m`\n\n**Scopes:**\n`flows:read`\n`lists:read`",
        "tags": [
          "Lists"
        ],
        "x-klaviyo-operation-aliases": [
          "get_flow_triggers_for_list",
          "get_list_flow_triggers"
        ],
        "x-klaviyo-pre-release": "None",
        "x-klaviyo-ratelimit": {
          "burst": "3/s",
          "steady": "60/m"
        },
        "x-klaviyo-scopes": [
          "flows:read",
          "lists:read"
        ]
      }
    },
    "/api/lists/{id}/relationships/flow-triggers": {
      "get": {
        "operationId": "get_ids_for_flows_triggered_by_list",
        "summary": "Get IDs for Flows Triggered by List",
        "description": "Get the IDs of all flows where the given list is being used as the trigger.<br><br>*Rate limits*:<br>Burst: `3/s`<br>Steady: `60/m`\n\n**Scopes:**\n`flows:read`\n`lists:read`",
        "tags": [
          "Lists"
        ],
        "x-klaviyo-operation-aliases": [
          "get_flow_trigger_ids_for_list",
          "get_list_relationships_flow_triggers"
        ],
        "x-klaviyo-pre-release": "None",
        "x-klaviyo-ratelimit": {
          "burst": "3/s",
          "steady": "60/m"
        },
        "x-klaviyo-scopes": [
          "flows:read",
          "lists:read"
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "Klaviyo-API-Key": {
        "type": "apiKey",
        "in": "header",
        "name": "Authorization",
        "description": "Private key authentication for /api/ endpoints is performed by setting the `Authorization` header to `Klaviyo-API-Key your-private-api-key`<br>For more information please visit https://developers.klaviyo.com/en/v2026-04-15/reference/api-overview#authentication",
        "x-default": "Klaviyo-API-Key your-private-api-key"
      }
    }
  },
  "tags": [
    {
      "name": "Lists",
      "description": "lists"
    }
  ]
}
